extra_deps = [
    ":rustc_abi-0.0.0",
    ":rustc_ast-0.0.0",
    ":rustc_attr_parsing-0.0.0",
    ":rustc_const_eval-0.0.0",
    ":rustc_data_structures-0.0.0",
    ":rustc_driver-0.0.0",
    ":rustc_errors-0.0.0",
    ":rustc_hir-0.0.0",
    ":rustc_hir_analysis-0.0.0",
    ":rustc_hir_typeck-0.0.0",
    ":rustc_index-0.0.0",
    ":rustc_infer-0.0.0",
    ":rustc_lexer-0.0.0",
    ":rustc_lint-0.0.0",
    ":rustc_middle-0.0.0",
    ":rustc_mir_dataflow-0.0.0",
    ":rustc_session-0.0.0",
    ":rustc_span-0.0.0",
    ":rustc_trait_selection-0.0.0",
    ":smallvec-1.15.1",
]
